### ISSUE TITLE
dnCNV button does not work

### ISSUE THREAD

**Issue by cluhaowie** [cluhaowie/VizCNV#14]
The app crash when pressing the show dnCNV button. In the Rstudio console, the error shows:
'Error in h: error in evaluating the argument 'x' in selecting a method for function 'as.data.frame': could not find function "subtract"'
@clifflun Can you specify the package where the 'subtract' function coming from?

**Comment by clifflun** [comment]
subtract is from the latest version of GenomicRanges

R also has to be above 4.2 for this to work properly. Ideally you download the R 4.2.2 version

in base R CLI (not RStudio):
install.packages("installr")
library(installr)
updateR()

**Comment by cluhaowie** [comment]
Got it. The R version on my end is 4.1.2.
