### ISSUE TITLE
error when trying to plot Baf

### ISSUE THREAD

**Issue by clifflun** [cluhaowie/VizCNV#17]
@cluhaowie 

Warning: Error in filter: In argument: `chrom %in% c(chr, paste0("chr", chr))`.
Caused by error in `h()`:
! error in evaluating the argument 'x' in selecting a method for function '%in%': object 'chrom' not found

I suspect it is calling the wrong reactiveValues variable

**Comment by cluhaowie** [comment]
values$ref value does not match with input$ref in line 75, I fixed the error
